version: "3"

services:
  genenv:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: setup
      args:
        PYTHON_IMAGE_TAG: "3.11.5"
        POETRY_VERSION: "1.6.1"
    tty: true
    image: genenv
    container_name: genenv
    volumes:
      - ./web:/app
    working_dir: /app
    command: /bin/bash -c "poetry run task generate_env"
    profiles:
      - setup

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: local_runner
      args:
        PYTHON_IMAGE_TAG: "3.11.5"
        POETRY_VERSION: "1.6.1"
    image: dj-todo-web
    container_name: dj-todo-web
    tty: true
    volumes:
      - ./web:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - READ_DJANGO_ENV_FILE=true
    # Run local server command
    # command: /bin/bash -c "poetry run task start_local"
    profiles:
      - local
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        POSTGRESQL_IMAGE_TAG: "16.0-alpine3.18"
    image: dj-todo-db
    container_name: dj-todo-db
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env
    profiles:
      - local
